#pragma once
#define pl "polish"
//#define eng "english" //uncomment this line and comment line 2 to change language
#pragma region polish
#ifdef pl
#define un_azymuth "azymut" //short from universal azymuth
#define un_altitude "wysokosc"
#define un_declination "deklinacja"
#define un_right_ascension "rektascensja"
#define un_year "rok"
#define un_month "miesiac"
#define un_time_utc "czas UTC"
#define un_day "dzien"
#define un_calibration "kalibracja"
#define un_laser_angle "kat_lasera"
#define un_second "sekunda"
#define un_dev_AZ "Azym.urz."
#define un_eq "EQ-"
#define un_lat "szer."
#define un_long "dlug."
#define un_set_mag_declination "Ustw.mag.deklinacje"
#define un_magnetic_declination "magnetyczna deklinacja"
#define un_your_location "twoja lok."
#define un_submit_continue "potwierdz/kontynuuj"
#define un_star_location "wsp. gwiazdy"
#define un_instruction "instrukcja:"
#define un_setting_1_RA "1- RA"
#define un_setting_2_DEC "2- DEC"
#define un_setting_play "play- zakoncz"
#define un_enter_star_ra "wprowadz rektascensje gwiazdy"
#define un_enter_star_dec "wprowadz deklinacje gwiazdy"
#define un_enter_latitude "wprowadz szerokosc geograficzna"
#define un_enter_longitude "wprowadz dlugosc geograficzna"
#define un_enter_accel_offset "wprowadz offset akcelerometru"
#define un_enter_az_offset "wprowadz offset azymutu"
#define un_star_visibility "widocznosc gwiazdy:"
#define un_visible "widoczna"
#define un_unvisible "nie widoczna"
#define un_motor1 "silnik 1"
#define un_motor2 "silnik 2"
#define un_degree "kat"
#define un_device_position_calibration "kalibracja pozycji urzadzenia"
#define un_pointing_at_north "gotowe, wskazujesz polnoc"
#define un_not_pointing_at_north "nie wskazujesz polnocy"
#define un_start_tracking_continously "zacznij sledzic gwiazde"
#define un_star_found "znaleziono gwiazde"
#define un_no_gps "brak gps"
#define un_no_satelites "brak satelit"
#define un_local_time "czas lokalny"
#define un_time_from_gps "czas gps"
#define un_can_calibrate "{1}"
#define un_cant_calibrate "{0}"
#define un_recent_location "ostatnia lokalizacja"
#define un_recently_tracked_star "ostatnia gwiazda"
#endif
#pragma endregion polish
#pragma region english
#ifdef eng
#define un_azymuth "azymuth" //short from universal azymuth
#define un_altitude "altitude"
#define un_declination "declination"
#define un_right_ascension "right asc."
#define un_year "year"
#define un_time_utc "UTC"
#define un_day "day"
#define un_calibration "calibration"
#define un_laser_angle "laser angle"
#define un_second "second"
#define un_dev_AZ "dev Az."
#define un_eq "EQ-"
#define un_month "month"
#define un_lat "lat."
#define un_long "long."
#define un_set_mag_declination "set mag. declination"
#define un_your_location "location"
#define un_submit_continue "confirm/continue"
#define un_star_location "star.loc."
#define un_instruction "instruction:"
#define un_setting_1_RA "1- RA"
#define un_setting_2_DEC "2- DEC"
#define un_setting_play "play- finish"
#define un_enter_star_ra "enter Star RA"
#define un_enter_star_dec "enter Star Dec"
#define un_enter_latitude "enter your latitude"
#define un_enter_longitude "enter your longitude"
#define un_enter_accel_offset "enter accel offset"
#define un_enter_az_offset "enter azymuth offset"
#define un_magnetic_declination "magnetic declination"
#define un_star_visibility "star visibility"
#define un_visible "visible"
#define un_unvisible "not visible"
#define un_motor1 "motor 1"
#define un_motor2 "motor 2"
#define un_degree "degree"
#define un_device_position_calibration "device position calibration"
#define un_pointing_at_north "ready, poining at north"
#define un_not_pointing_at_north "not pointing at north"
#define un_start_tracking_continously "start star tracking"
#define un_star_found "star found"
#define un_no_gps "no gps"
#define un_no_satelites "no satelites"
#define un_local_time "local time"
#define un_time_from_gps "gps time"
#define un_can_calibrate "{1}"
#define un_cant_calibrate "{0}"
#define un_recent_location "recent location"
#define un_recently_tracked_star "recent star"
#endif

#pragma endregion english